### PR TITLE
Change http_content to Rc in HttpWrapper

### PR DESCRIPTION
**Pull request by 007gzs**

### CODE REVIEW

**Comment by johnlanni** [comment]
cc @jizhuozhi @Lynskylate

**Comment by johnlanni** [comment]
@007gzs Please fix the CI.

**Review by jizhuozhi — APPROVED** [review]
LGTM

**Review by johnlanni — APPROVED** [review]
LGTM

**Comment by jizhuozhi** [comment]
PTAL @007gzs 
```console
182 | downcast_rs::impl_downcast!(HttpContextWrapper<PluginConfig> where PluginConfig: Default + DeserializeOwned + Clone+Sized);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | |
    | the trait `Sized` is not implemented for `(dyn HttpContextWrapper<PluginConfig> + 'static)`, which is required by `(dyn HttpContextWrapper<PluginConfig> + 'static): Downcast`
    | required by a bound introduced by this call
    |
    = note: required for `(dyn HttpContextWrapper<PluginConfig> + 'static)` to implement `Downcast`
    = note: this error originates in the macro `impl_downcast` which comes from the expansion of the macro `downcast_rs::impl_downcast` (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Comment by 007gzs** [comment]
> PTAL @007gzs
> 
> ```
> 182 | downcast_rs::impl_downcast!(HttpContextWrapper<PluginConfig> where PluginConfig: Default + DeserializeOwned + Clone+Sized);
>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     | |
>     | the trait `Sized` is not implemented for `(dyn HttpContextWrapper<PluginConfig> + 'static)`, which is required by `(dyn HttpContextWrapper<PluginConfig> + 'static): Downcast`
>     | required by a bound introduced by this call
>     |
>     = note: required for `(dyn HttpContextWrapper<PluginConfig> + 'static)` to implement `Downcast`
>     = note: this error originates in the macro `impl_downcast` which comes from the expansion of the macro `downcast_rs::impl_downcast` (in Nightly builds, run with -Z macro-backtrace for more info)
> ```

what's you rust version, it may run ok when rust>=1.80  https://github.com/alibaba/higress/blob/main/plugins/wasm-rust/Dockerfile

**Comment by jizhuozhi** [comment]
cargo 1.80.1 (376290515 2024-07-16)

**Comment by 007gzs** [comment]
https://github.com/alibaba/higress/blob/main/plugins/wasm-rust/src/plugin_wrapper.rs#L182 这里没有sized把，是你单独加的么

**Comment by 007gzs** [comment]
run `rm Cargo.lock && cargo clean` in you plugin path

**Pull request merged**
