### PR TITLE
feat: support only build one plugin to testing specified WasmPlugin

### PR DESCRIPTION
**Pull request by Hinsteny**
### Ⅰ. Describe what this PR did
Support only build one plugin to testing specified WasmPlugin

### Ⅱ. Does this pull request fix one issue?

No

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
no need

### Ⅳ. Describe how to verify it
make ingress-wasmplugin-test
PLUGIN_NAME=request-block make ingress-wasmplugin-test

### Ⅴ. Special notes for reviews
No

### CODE REVIEW

**Comment by Hinsteny** [comment]
@Xunzhuo @johnlanni please help me to review this PR.

**Comment by Xunzhuo** [comment]
Can we test against multiple wasm plugins ? @Hinsteny

**Comment by Hinsteny** [comment]
> Can we test against multiple wasm plugins ? @Hinsteny
yes, we can. if no parameter of plugin name is specified, all plugins in the wasm-go extensions directory are compiled for testing by default.

**Review by johnlanni — APPROVED** [review]
LGTM

**Review by Xunzhuo — APPROVED** [review]

**Pull request merged**
