### PR TITLE
AI proxy return unified status in header phase

### PR DESCRIPTION
**Pull request by StarryVae**
### Ⅰ. Describe what this PR did

AI proxy return unified status in header phase.

https://github.com/alibaba/higress/issues/1584#issuecomment-2533553892

### CODE REVIEW

**Comment by StarryVae** [comment]
should we just return `ActionContinue` when there is no body here, or sendLocalReply? cc @johnlanni

**Comment by johnlanni** [comment]
> should we just return `ActionContinue` when there is no body here, or sendLocalReply? cc @johnlanni

Returning only "ActionContinue" is okay, as this leaves the handling of the response to the backend service.

**Comment by StarryVae** [comment]
ok, i think it is ready for review.

**Comment by johnlanni** [comment]
It seems that all providers no longer need to worry about the return value of the status code. Can we uniformly adjust the interfaces of all providers?

**Comment by StarryVae** [comment]
emm, yeah, i will adjust the `OnRequestHeaders` of all providers.

**Comment by StarryVae** [comment]
image

build docker image: higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/wasm-go-builder:go1.20.14-tinygo0.29.0-oras1.0.0

**Comment by johnlanni** [comment]
Is your PC an ARM architecture? This image likely does not support ARM architecture

**Comment by johnlanni** [comment]
Inspect It seems that it is now a multi-architecture image, and I can also compile under ARM, what is your machine environment?

image

**Comment by StarryVae** [comment]
my environment is just x86

**Comment by StarryVae** [comment]
i checkout to v2.0.3, it can work

**Comment by StarryVae** [comment]
it can work now, but i have no idea why 😆 , anyway, i can compile now, thanks.

**Comment by StarryVae** [comment]
@johnlanni PTAL, thanks.

**Review by johnlanni — APPROVED** [review]
LGTM, Thanks!

**Comment by StarryVae** [comment]
i have rebased the main branch

**Pull request merged**
