### PR TITLE
feature: E2E framework supports testing wasm plugins

### PR DESCRIPTION
**Pull request by Hinsteny**
### Ⅰ. Describe what this PR did
Finished E2E framework supports testing wasm plugins function.  [issue](https://github.com/alibaba/higress/issues/342)

### Ⅱ. Does this pull request fix one issue?

No

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
yes, had added.

### Ⅳ. Describe how to verify it
make wasmplugins test

### Ⅴ. Special notes for reviews
None

### CODE REVIEW

**Comment by Hinsteny** [comment]
@Xunzhuo @johnlanni please help me to review this PR.

**Review by Xunzhuo — COMMENTED** [review]
Why not enable it in build and test workflow?

**Comment by Hinsteny** [comment]
> Why not enable it in build and test workflow?

Because the wasmplugins building is time-consuming, so i separate the api test and wasmplugin test.

**Comment by Xunzhuo** [comment]
@Hinsteny yes I get it, but why not enable the wasm-conformance-test in CI ?

**Comment by Hinsteny** [comment]
> 

@Xunzhuo Just added it, please check.

**Comment by Xunzhuo** [comment]
https://github.com/alibaba/higress/actions/runs/5206737597/jobs/9393699575?pr=369

**Comment by Xunzhuo** [comment]
https://github.com/alibaba/higress/actions/runs/5206737597

**Review by Xunzhuo — APPROVED** [review]
LGTM. Good job

**Pull request merged**
