### PR TITLE
feat: supports custom prepare build script

### PR DESCRIPTION
**Pull request by jizhuozhi**
### Ⅰ. Describe what this PR did

Nowadays, if some plugin has additional dependencies need to be installed, developer may change the builder Dockerfile directly, but it's not healthy for long time maintaining.

This PR will support custom prepare build script for each plugin.

### CODE REVIEW

**Review by johnlanni — CHANGES_REQUESTED** [review]
The action also needs to be updated accordingly:

https://github.com/alibaba/higress/blob/aee37c5e22670b11ba88d1939b8c77dde0f9da68/.github/workflows/build-and-push-wasm-plugin-image.yaml#L133

**Comment by 007gzs** [comment]
默认脚本是不是可以放在.buildrc里，和go保持一致

**Comment by 007gzs** [comment]
> The action also needs to be updated accordingly:
> 
> https://github.com/alibaba/higress/blob/aee37c5e22670b11ba88d1939b8c77dde0f9da68/.github/workflows/build-and-push-wasm-plugin-image.yaml#L133

昨天看了下，gcc那些依赖是ai-data-masking项目里的正则库依赖的，不是一个通用依赖

**Comment by johnlanni** [comment]
> > The action also needs to be updated accordingly:
> > https://github.com/alibaba/higress/blob/aee37c5e22670b11ba88d1939b8c77dde0f9da68/.github/workflows/build-and-push-wasm-plugin-image.yaml#L133
> 
> 昨天看了下，gcc那些依赖是ai-data-masking项目里的正则库依赖的，不是一个通用依赖

是的，我的意思是要在这里增加支持 prepare 脚本的逻辑

**Comment by 007gzs** [comment]
参考这里
https://github.com/alibaba/higress/blob/aee37c5e22670b11ba88d1939b8c77dde0f9da68/.github/workflows/build-and-push-wasm-plugin-image.yaml#L111-L117

**Comment by 007gzs** [comment]
go也没有修改 prepare 脚本的逻辑把，rust和go可以统一固定为插件目录下的 .buildrc

**Comment by jizhuozhi** [comment]
改成.buildrc了

**Review by 007gzs — APPROVED** [review]
LGTM

**Comment by jizhuozhi** [comment]
There is a change request and no relation with fixed PR but no way to resolve it, PTAL @johnlanni

**Review by johnlanni — APPROVED** [review]
LGTM

**Pull request merged**
