### PR TITLE
fix: fix kubetype-gen for http2rpc wrong plural value issue

### PR DESCRIPTION
**Pull request by Hinsteny**
### Ⅰ. Describe what this PR did
fix kubetype-gen for http2rpc wrong plural value issue

### Ⅱ. Does this pull request fix one issue?
NO

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
NO

### Ⅳ. Describe how to verify it
NO

### Ⅴ. Special notes for reviews
NO

### CODE REVIEW

**Review by johnlanni — CHANGES_REQUESTED** [review]
@Hinsteny You need re-run the `make gen-api` to generate the crd file.

**Comment by Hinsteny** [comment]
> 

yes, i had done that. There has no change for the crd file as expected.

**Comment by johnlanni** [comment]
> > 
> 
> yes, i had done that. There has no change for the crd file as expected.

oh, right

**Review by johnlanni — APPROVED** [review]
LGTM

**Pull request merged**
